"""Alembic script.py.mako template."""
"""initial_schema

Revision ID: dca8bfccda56
Revises: 
Create Date: 2026-04-10 01:35:39.028807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca8bfccda56'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYSTE', name='role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_table('rapports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=500), nullable=False),
    sa.Column('format', sa.Enum('pdf', 'docx', 'xlsx', name='format_enum'), nullable=False),
    sa.Column('chemin', sa.String(length=1000), nullable=False),
    sa.Column('statut', sa.Enum('en_attente', 'en_cours', 'termine', 'erreur', name='statut_rapport_enum'), nullable=False),
    sa.Column('uploade_par', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploade_par'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rapport_id', sa.UUID(), nullable=False),
    sa.Column('lance_par', sa.UUID(), nullable=False),
    sa.Column('resume_executif', sa.Text(), nullable=True),
    sa.Column('score_maturite', sa.Float(), nullable=True),
    sa.Column('statut', sa.Enum('en_cours', 'termine', 'erreur', name='statut_analyse_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lance_par'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['rapport_id'], ['rapports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultats_conformite',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analyse_id', sa.UUID(), nullable=False),
    sa.Column('referentiel', sa.Enum('ISO27001', 'RGPD', 'LOI0908', name='referentiel_enum'), nullable=False),
    sa.Column('domaine', sa.String(length=500), nullable=True),
    sa.Column('statut', sa.Enum('CONFORME', 'NON_CONFORME', 'PARTIEL', name='statut_conformite_enum'), nullable=False),
    sa.Column('ecart', sa.Text(), nullable=True),
    sa.Column('taux_conformite', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['analyse_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risques',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analyse_id', sa.UUID(), nullable=False),
    sa.Column('libelle', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('categorie', sa.Enum('CYBER', 'OPERATIONNEL', 'LEGAL', 'FINANCIER', 'RH', name='categorie_risque_enum'), nullable=False),
    sa.Column('probabilite', sa.Integer(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('score_risque', sa.Float(), nullable=False),
    sa.Column('severite', sa.Enum('CRITIQUE', 'ELEVE', 'MOYEN', 'FAIBLE', name='severite_enum'), nullable=False),
    sa.Column('section_source', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['analyse_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommandations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analyse_id', sa.UUID(), nullable=False),
    sa.Column('risque_id', sa.UUID(), nullable=True),
    sa.Column('libelle', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priorite', sa.Enum('CRITIQUE', 'HAUTE', 'MOYENNE', 'FAIBLE', name='priorite_enum'), nullable=False),
    sa.Column('type_action', sa.Enum('QUICK_WIN', 'LONG_TERME', name='type_action_enum'), nullable=False),
    sa.Column('effort_estime', sa.Enum('FAIBLE', 'MOYEN', 'ELEVE', name='effort_enum'), nullable=False),
    sa.Column('statut', sa.Enum('A_FAIRE', 'EN_COURS', 'CLOTURE', name='statut_recommandation_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analyse_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['risque_id'], ['risques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommandations')
    op.drop_table('risques')
    op.drop_table('resultats_conformite')
    op.drop_table('analyses')
    op.drop_table('rapports')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    # ### end Alembic commands ###
